stages:
  - checking

clang-format:
  stage: checking
  script:
    - git clone http://git.home.lan/root/check-clang-format.git
    - cp check-clang-format/check-clang-format.py .
    - python3 check-clang-format.py -r .
